services:
  db:
    image: postgres
    container_name: shop24_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
   
  seq:
    image: datalust/seq:latest
    ports:
      - '80:80'
      - '5341:5341'
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True

  rabbitmq:
    image: rabbitmq:3-management # Uses the image with the management UI
    ports:
      - "5672:5672" # Standard AMQP port for client connections
      - "15672:15672" # Port for the RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest # Default username (change for production)
      RABBITMQ_DEFAULT_PASS: guest # Default password (change for production)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persist RabbitMQ data
    hostname: rabbitmq # Defines the hostname within the Docker network

volumes:
  local_pgdata:
  pgadmin-data:
  rabbitmq_data: # Declares a named volume for data persistence